package com.jrome.crud.bean;

import java.util.ArrayList;
import java.util.List;

public class EUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public EUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidIsNull() {
            addCriterion("uId is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uId is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uId =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uId <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uId >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uId >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uId <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uId <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uId in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uId not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uId between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uId not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUnameIsNull() {
            addCriterion("uName is null");
            return (Criteria) this;
        }

        public Criteria andUnameIsNotNull() {
            addCriterion("uName is not null");
            return (Criteria) this;
        }

        public Criteria andUnameEqualTo(String value) {
            addCriterion("uName =", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotEqualTo(String value) {
            addCriterion("uName <>", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThan(String value) {
            addCriterion("uName >", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThanOrEqualTo(String value) {
            addCriterion("uName >=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThan(String value) {
            addCriterion("uName <", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThanOrEqualTo(String value) {
            addCriterion("uName <=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLike(String value) {
            addCriterion("uName like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotLike(String value) {
            addCriterion("uName not like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameIn(List<String> values) {
            addCriterion("uName in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotIn(List<String> values) {
            addCriterion("uName not in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameBetween(String value1, String value2) {
            addCriterion("uName between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotBetween(String value1, String value2) {
            addCriterion("uName not between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUgenderIsNull() {
            addCriterion("uGender is null");
            return (Criteria) this;
        }

        public Criteria andUgenderIsNotNull() {
            addCriterion("uGender is not null");
            return (Criteria) this;
        }

        public Criteria andUgenderEqualTo(String value) {
            addCriterion("uGender =", value, "ugender");
            return (Criteria) this;
        }

        public Criteria andUgenderNotEqualTo(String value) {
            addCriterion("uGender <>", value, "ugender");
            return (Criteria) this;
        }

        public Criteria andUgenderGreaterThan(String value) {
            addCriterion("uGender >", value, "ugender");
            return (Criteria) this;
        }

        public Criteria andUgenderGreaterThanOrEqualTo(String value) {
            addCriterion("uGender >=", value, "ugender");
            return (Criteria) this;
        }

        public Criteria andUgenderLessThan(String value) {
            addCriterion("uGender <", value, "ugender");
            return (Criteria) this;
        }

        public Criteria andUgenderLessThanOrEqualTo(String value) {
            addCriterion("uGender <=", value, "ugender");
            return (Criteria) this;
        }

        public Criteria andUgenderLike(String value) {
            addCriterion("uGender like", value, "ugender");
            return (Criteria) this;
        }

        public Criteria andUgenderNotLike(String value) {
            addCriterion("uGender not like", value, "ugender");
            return (Criteria) this;
        }

        public Criteria andUgenderIn(List<String> values) {
            addCriterion("uGender in", values, "ugender");
            return (Criteria) this;
        }

        public Criteria andUgenderNotIn(List<String> values) {
            addCriterion("uGender not in", values, "ugender");
            return (Criteria) this;
        }

        public Criteria andUgenderBetween(String value1, String value2) {
            addCriterion("uGender between", value1, value2, "ugender");
            return (Criteria) this;
        }

        public Criteria andUgenderNotBetween(String value1, String value2) {
            addCriterion("uGender not between", value1, value2, "ugender");
            return (Criteria) this;
        }

        public Criteria andUemailIsNull() {
            addCriterion("uEmail is null");
            return (Criteria) this;
        }

        public Criteria andUemailIsNotNull() {
            addCriterion("uEmail is not null");
            return (Criteria) this;
        }

        public Criteria andUemailEqualTo(String value) {
            addCriterion("uEmail =", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotEqualTo(String value) {
            addCriterion("uEmail <>", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailGreaterThan(String value) {
            addCriterion("uEmail >", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailGreaterThanOrEqualTo(String value) {
            addCriterion("uEmail >=", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailLessThan(String value) {
            addCriterion("uEmail <", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailLessThanOrEqualTo(String value) {
            addCriterion("uEmail <=", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailLike(String value) {
            addCriterion("uEmail like", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotLike(String value) {
            addCriterion("uEmail not like", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailIn(List<String> values) {
            addCriterion("uEmail in", values, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotIn(List<String> values) {
            addCriterion("uEmail not in", values, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailBetween(String value1, String value2) {
            addCriterion("uEmail between", value1, value2, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotBetween(String value1, String value2) {
            addCriterion("uEmail not between", value1, value2, "uemail");
            return (Criteria) this;
        }

        public Criteria andUphoneIsNull() {
            addCriterion("uPhone is null");
            return (Criteria) this;
        }

        public Criteria andUphoneIsNotNull() {
            addCriterion("uPhone is not null");
            return (Criteria) this;
        }

        public Criteria andUphoneEqualTo(String value) {
            addCriterion("uPhone =", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneNotEqualTo(String value) {
            addCriterion("uPhone <>", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneGreaterThan(String value) {
            addCriterion("uPhone >", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneGreaterThanOrEqualTo(String value) {
            addCriterion("uPhone >=", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneLessThan(String value) {
            addCriterion("uPhone <", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneLessThanOrEqualTo(String value) {
            addCriterion("uPhone <=", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneLike(String value) {
            addCriterion("uPhone like", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneNotLike(String value) {
            addCriterion("uPhone not like", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneIn(List<String> values) {
            addCriterion("uPhone in", values, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneNotIn(List<String> values) {
            addCriterion("uPhone not in", values, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneBetween(String value1, String value2) {
            addCriterion("uPhone between", value1, value2, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneNotBetween(String value1, String value2) {
            addCriterion("uPhone not between", value1, value2, "uphone");
            return (Criteria) this;
        }

        public Criteria andUpwdIsNull() {
            addCriterion("uPwd is null");
            return (Criteria) this;
        }

        public Criteria andUpwdIsNotNull() {
            addCriterion("uPwd is not null");
            return (Criteria) this;
        }

        public Criteria andUpwdEqualTo(String value) {
            addCriterion("uPwd =", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdNotEqualTo(String value) {
            addCriterion("uPwd <>", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdGreaterThan(String value) {
            addCriterion("uPwd >", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdGreaterThanOrEqualTo(String value) {
            addCriterion("uPwd >=", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdLessThan(String value) {
            addCriterion("uPwd <", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdLessThanOrEqualTo(String value) {
            addCriterion("uPwd <=", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdLike(String value) {
            addCriterion("uPwd like", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdNotLike(String value) {
            addCriterion("uPwd not like", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdIn(List<String> values) {
            addCriterion("uPwd in", values, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdNotIn(List<String> values) {
            addCriterion("uPwd not in", values, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdBetween(String value1, String value2) {
            addCriterion("uPwd between", value1, value2, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdNotBetween(String value1, String value2) {
            addCriterion("uPwd not between", value1, value2, "upwd");
            return (Criteria) this;
        }

        public Criteria andUscoreIsNull() {
            addCriterion("uScore is null");
            return (Criteria) this;
        }

        public Criteria andUscoreIsNotNull() {
            addCriterion("uScore is not null");
            return (Criteria) this;
        }

        public Criteria andUscoreEqualTo(String value) {
            addCriterion("uScore =", value, "uscore");
            return (Criteria) this;
        }

        public Criteria andUscoreNotEqualTo(String value) {
            addCriterion("uScore <>", value, "uscore");
            return (Criteria) this;
        }

        public Criteria andUscoreGreaterThan(String value) {
            addCriterion("uScore >", value, "uscore");
            return (Criteria) this;
        }

        public Criteria andUscoreGreaterThanOrEqualTo(String value) {
            addCriterion("uScore >=", value, "uscore");
            return (Criteria) this;
        }

        public Criteria andUscoreLessThan(String value) {
            addCriterion("uScore <", value, "uscore");
            return (Criteria) this;
        }

        public Criteria andUscoreLessThanOrEqualTo(String value) {
            addCriterion("uScore <=", value, "uscore");
            return (Criteria) this;
        }

        public Criteria andUscoreLike(String value) {
            addCriterion("uScore like", value, "uscore");
            return (Criteria) this;
        }

        public Criteria andUscoreNotLike(String value) {
            addCriterion("uScore not like", value, "uscore");
            return (Criteria) this;
        }

        public Criteria andUscoreIn(List<String> values) {
            addCriterion("uScore in", values, "uscore");
            return (Criteria) this;
        }

        public Criteria andUscoreNotIn(List<String> values) {
            addCriterion("uScore not in", values, "uscore");
            return (Criteria) this;
        }

        public Criteria andUscoreBetween(String value1, String value2) {
            addCriterion("uScore between", value1, value2, "uscore");
            return (Criteria) this;
        }

        public Criteria andUscoreNotBetween(String value1, String value2) {
            addCriterion("uScore not between", value1, value2, "uscore");
            return (Criteria) this;
        }

        public Criteria andUrankingIsNull() {
            addCriterion("uRanking is null");
            return (Criteria) this;
        }

        public Criteria andUrankingIsNotNull() {
            addCriterion("uRanking is not null");
            return (Criteria) this;
        }

        public Criteria andUrankingEqualTo(String value) {
            addCriterion("uRanking =", value, "uranking");
            return (Criteria) this;
        }

        public Criteria andUrankingNotEqualTo(String value) {
            addCriterion("uRanking <>", value, "uranking");
            return (Criteria) this;
        }

        public Criteria andUrankingGreaterThan(String value) {
            addCriterion("uRanking >", value, "uranking");
            return (Criteria) this;
        }

        public Criteria andUrankingGreaterThanOrEqualTo(String value) {
            addCriterion("uRanking >=", value, "uranking");
            return (Criteria) this;
        }

        public Criteria andUrankingLessThan(String value) {
            addCriterion("uRanking <", value, "uranking");
            return (Criteria) this;
        }

        public Criteria andUrankingLessThanOrEqualTo(String value) {
            addCriterion("uRanking <=", value, "uranking");
            return (Criteria) this;
        }

        public Criteria andUrankingLike(String value) {
            addCriterion("uRanking like", value, "uranking");
            return (Criteria) this;
        }

        public Criteria andUrankingNotLike(String value) {
            addCriterion("uRanking not like", value, "uranking");
            return (Criteria) this;
        }

        public Criteria andUrankingIn(List<String> values) {
            addCriterion("uRanking in", values, "uranking");
            return (Criteria) this;
        }

        public Criteria andUrankingNotIn(List<String> values) {
            addCriterion("uRanking not in", values, "uranking");
            return (Criteria) this;
        }

        public Criteria andUrankingBetween(String value1, String value2) {
            addCriterion("uRanking between", value1, value2, "uranking");
            return (Criteria) this;
        }

        public Criteria andUrankingNotBetween(String value1, String value2) {
            addCriterion("uRanking not between", value1, value2, "uranking");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table euser
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 26 22:21:04 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}