package com.jrome.crud.bean;

public class EUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euser.uId
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euser.uName
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euser.uGender
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    private String ugender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euser.uEmail
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    private String uemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euser.uPhone
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    private String uphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euser.uPwd
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    private String upwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euser.uScore
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    private String uscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euser.uRanking
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    private String uranking;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euser.uId
     *
     * @return the value of euser.uId
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euser.uId
     *
     * @param uid the value for euser.uId
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euser.uName
     *
     * @return the value of euser.uName
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euser.uName
     *
     * @param uname the value for euser.uName
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euser.uGender
     *
     * @return the value of euser.uGender
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public String getUgender() {
        return ugender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euser.uGender
     *
     * @param ugender the value for euser.uGender
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public void setUgender(String ugender) {
        this.ugender = ugender == null ? null : ugender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euser.uEmail
     *
     * @return the value of euser.uEmail
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public String getUemail() {
        return uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euser.uEmail
     *
     * @param uemail the value for euser.uEmail
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public void setUemail(String uemail) {
        this.uemail = uemail == null ? null : uemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euser.uPhone
     *
     * @return the value of euser.uPhone
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public String getUphone() {
        return uphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euser.uPhone
     *
     * @param uphone the value for euser.uPhone
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public void setUphone(String uphone) {
        this.uphone = uphone == null ? null : uphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euser.uPwd
     *
     * @return the value of euser.uPwd
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euser.uPwd
     *
     * @param upwd the value for euser.uPwd
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd == null ? null : upwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euser.uScore
     *
     * @return the value of euser.uScore
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public String getUscore() {
        return uscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euser.uScore
     *
     * @param uscore the value for euser.uScore
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public void setUscore(String uscore) {
        this.uscore = uscore == null ? null : uscore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euser.uRanking
     *
     * @return the value of euser.uRanking
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public String getUranking() {
        return uranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euser.uRanking
     *
     * @param uranking the value for euser.uRanking
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    public void setUranking(String uranking) {
        this.uranking = uranking == null ? null : uranking.trim();
    }
}