package com.jrome.crud.dao;

import com.jrome.crud.bean.Empoyee;
import com.jrome.crud.bean.EmpoyeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpoyeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 16 23:39:22 CST 2018
     */
    long countByExample(EmpoyeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 16 23:39:22 CST 2018
     */
    int deleteByExample(EmpoyeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 16 23:39:22 CST 2018
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 16 23:39:22 CST 2018
     */
    int insert(Empoyee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 16 23:39:22 CST 2018
     */
    int insertSelective(Empoyee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 16 23:39:22 CST 2018
     */
    List<Empoyee> selectByExample(EmpoyeeExample example);
    List<Empoyee> selectByExampleWithDept(EmpoyeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 16 23:39:22 CST 2018
     */
    Empoyee selectByPrimaryKey(Integer empId);
    Empoyee selectByPrimaryKeyWithDept(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 16 23:39:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Empoyee record, @Param("example") EmpoyeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 16 23:39:22 CST 2018
     */
    int updateByExample(@Param("record") Empoyee record, @Param("example") EmpoyeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 16 23:39:22 CST 2018
     */
    int updateByPrimaryKeySelective(Empoyee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 16 23:39:22 CST 2018
     */
    int updateByPrimaryKey(Empoyee record);
}