package com.jrome.crud.dao;

import com.jrome.crud.bean.EUser;
import com.jrome.crud.bean.EUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    long countByExample(EUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    int deleteByExample(EUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    int insert(EUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    int insertSelective(EUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    List<EUser> selectByExample(EUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    EUser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") EUser record, @Param("example") EUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    int updateByExample(@Param("record") EUser record, @Param("example") EUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    int updateByPrimaryKeySelective(EUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated Mon Nov 26 22:21:04 CST 2018
     */
    int updateByPrimaryKey(EUser record);
}